### ISSUE TITLE
Add a global/default config setting

### ISSUE THREAD

**Issue by mikhail** [Nextdoor/zkmonitor#17]
The yaml file should be able to specify some global settings that do not need to be passed to individual paths. Example:

```
defaults:
  cancel_timeout: 1
  children: 1
  alerter:
    email: engineering@company.com
    hipchat:
      room: engineering
      token: <token>
/foo/path/min_1:
  alerter:
    email:
    hipchat:
      room: Ops
/bar/path/min_2:
  children: 2
```
